FROM dockerhub.genostack.com:8090/base/miniconda3:base_py310_libpq

WORKDIR /workspace
# 这里需要安装项目依赖的软件，并且确定这些软件不会经常变更

# docker build -t dockerhub.genostack.com:8090/jikai/{{cookiecutter.repo_name}}:base_v01 .
